### ISSUE TITLE
some wrong

### ISSUE THREAD

**Issue by Bohr-niels** [mdtanker/RIS_basement_sediment#1]
Hello, @mdtanker, there are some errors occur when I run your code, I think the error is caused by the add_map_features() function, the code of the function is following:
<img width="933" alt="微信图片_20241117210008" src="https://github.com/user-attachments/assets/01caf83f-acda-4d71-9704-598a806c1587">
And the error message is:
![image](https://github.com/user-attachments/assets/a097c912-6931-496d-a6b7-de72ba9f93e7)
One purpose of the function is to add geographical graticules on the figure which uses the linear projection, as we can see, to achieve this purpose, you use the basemap module of pygmt, and the projection is set to Polar Stereographic projection (EPSG3031), but the region you set is the region which used in linear projection, and the error message seems to be due to this. Is the error caused by the different pygmt version? 
And if we can't add geographical graticules by this method, how can I add them to the linear projection figure? Thanks a lot.😁😁😁

**Comment by mdtanker** [comment]
Thanks for pointing this out! Since I made this repository I have switched all my plotting to use a Python package I created called PolarToolkit. It's basically a wrapper of PyGMT. Check out this function for adding lat long lines to a figure: https://polartoolkit.readthedocs.io/en/latest/_modules/polartoolkit/maps.html#add_gridlines

Let me know if that helps!

**Comment by Bohr-niels** [comment]
Oh, PolarToolkit helps me a lot! But I still have a question, when I plot bathymetry in Arctic Ocean, only a few lon and lat annotations are labeled, just like this:
![image](https://github.com/user-attachments/assets/6df4d67e-f93e-4ced-902a-aa51b6470714)
And I set x_spacing and y_spacing as 60 and 10, respectively, the projection of the fig is Polar Stereographic projection (EPSG3996): 
![image](https://github.com/user-attachments/assets/7f86242a-e50d-47be-9bb8-e0b14b6e324f)
this troubles me a lot.😣😣😣

**Comment by mdtanker** [comment]
Yes unfortunately I think that is a default setting in PyGMT since the labels would overlap, they are omitting some (I think). By default, it should plot a label for each x and y spacing you give. You can try copying and pasting the `add_gridlines` function and altering it in your code to see if you can figure out how to fix it. It is the `frame` parameter which controls the spacing of the gridlines and labels. See this for some more info: https://www.pygmt.org/dev/tutorials/basics/frames.html#sphx-glr-tutorials-basics-frames-py

**Comment by Bohr-niels** [comment]
Thanks! Your suggestions are so helpful.🤗
